import type {
  CelestialObject,
  SolarSystemBody,
  ExoplanetData,
  APODRecord,
} from '@/types/astronomy';

export const CELESTIAL_OBJECTS: CelestialObject[] = [
  {
    id: 'sgr-a-star',
    name: 'Sagittarius A*',
    catalogDesignation: 'Sgr A*',
    alternativeNames: ['Galactic Center Black Hole', '2MASS J17454004-2900279'],
    type: 'Black Hole',
    subType: 'Supermassive Black Hole',
    constellation: 'Sagittarius',
    coordinates: {
      ra: 266.4168,
      dec: -29.0078,
      raHMS: '17h 45m 40.0s',
      decDMS: '-29° 00\' 28"',
      frame: 'ICRS',
      distanceLy: 26673,
      distanceParsec: 8178,
      galacticL: 359.9443,
      galacticB: -0.0461,
    },
    massSolar: 4154000,
    massKg: '8.26e+36',
    radiusKm: 12000000,
    distanceLy: 26673,
    temperatureKelvin: 1e11,
    discoveryYear: 1974,
    discoverer: 'Bruce Balick and Robert L. Brown',
    description: 'The supermassive black hole at the dynamical center of our Milky Way galaxy, imaged by the Event Horizon Telescope in 2022.',
    scientificNotes: 'Mass derived from 20-year orbital astrometry of S-stars (notably S2) with the GRAVITY and Keck interferometers.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Event Horizon Telescope Collaboration (2022)', dataset: 'EHT mm-VLBI Array', sourceType: 'Observatory', url: 'https://eventhorizontelescope.org' },
      { name: 'GRAVITY Collaboration (2018) Detection of the gravitational redshift in the orbit of the star S2', sourceType: 'Peer-Reviewed Paper' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1200&q=80',
    color: '#F97316',
    featured: true,
  },
  {
    id: 'm31-andromeda',
    name: 'Andromeda Galaxy',
    catalogDesignation: 'Messier 31 / NGC 224',
    alternativeNames: ['M31', 'Andromeda Nebula'],
    type: 'Galaxy',
    subType: 'Barred Spiral Galaxy (SA(s)b)',
    constellation: 'Andromeda',
    coordinates: {
      ra: 10.6847,
      dec: 41.2687,
      raHMS: '00h 42m 44.3s',
      decDMS: '+41° 16\' 09"',
      frame: 'ICRS',
      distanceLy: 2537000,
      distanceParsec: 778000,
      galacticL: 121.1743,
      galacticB: -21.5728,
    },
    apparentMagnitude: 3.44,
    absoluteMagnitude: -21.5,
    distanceLy: 2537000,
    massSolar: 1.5e12,
    radiusKm: 1.04e18,
    discoveryYear: 964,
    discoverer: 'Abd al-Rahman al-Sufi (Book of Fixed Stars)',
    description: 'The nearest major spiral galaxy to the Milky Way, containing approximately one trillion stars and heading toward a collision in ~4.5 billion years.',
    scientificNotes: 'Cepheid variable period-luminosity relation measured by Edwin Hubble in 1923 conclusively proved M31 is an extragalactic island universe.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'NASA/IPAC Extragalactic Database (NED)', dataset: 'M31 Morphometry & Distance', sourceType: 'Catalog' },
      { name: 'Hubble Space Telescope Panchromatic Hubble Andromeda Treasury (PHAT)', sourceType: 'Observatory' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
    color: '#818CF8',
    featured: true,
  },
  {
    id: 'm42-orion-nebula',
    name: 'Orion Nebula',
    catalogDesignation: 'Messier 42 / NGC 1976',
    alternativeNames: ['M42', 'Great Nebula in Orion'],
    type: 'Nebula',
    subType: 'Diffuse Emission & Reflection Nebula',
    constellation: 'Orion',
    coordinates: {
      ra: 83.8221,
      dec: -5.3911,
      raHMS: '05h 35m 17.3s',
      decDMS: '-05° 23\' 28"',
      frame: 'ICRS',
      distanceLy: 1344,
      distanceParsec: 412,
      galacticL: 209.0137,
      galacticB: -19.3816,
    },
    apparentMagnitude: 4.0,
    distanceLy: 1344,
    massSolar: 2000,
    temperatureKelvin: 10000,
    discoveryYear: 1610,
    discoverer: 'Nicolas-Claude Fabri de Peiresc',
    description: 'One of the brightest diffuse nebulae and the closest region of massive star formation to Earth, illuminated by the young Trapezium Cluster.',
    scientificNotes: 'Intense ultraviolet radiation from O-type star Theta1 Orionis C photoionizes hydrogen gas, creating the prominent H-alpha emission glow.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Hubble Heritage Team (NASA/ESA)', dataset: 'M42 Mosaic', sourceType: 'Observatory' },
      { name: 'Very Long Baseline Array (VLBA) Trigonometric Parallaxes', sourceType: 'Peer-Reviewed Paper' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    color: '#EC4899',
    featured: true,
  },
  {
    id: 'betelgeuse',
    name: 'Betelgeuse',
    catalogDesignation: 'Alpha Orionis / HD 39801',
    alternativeNames: ['α Ori', 'HR 2061'],
    type: 'Star',
    subType: 'Red Supergiant (M1-2 Ia-ab)',
    constellation: 'Orion',
    coordinates: {
      ra: 88.7929,
      dec: 7.4071,
      raHMS: '05h 55m 10.3s',
      decDMS: '+07° 24\' 25"',
      frame: 'ICRS',
      distanceLy: 548,
      distanceParsec: 168,
      galacticL: 199.7872,
      galacticB: -8.9586,
    },
    apparentMagnitude: 0.5,
    absoluteMagnitude: -5.85,
    distanceLy: 548,
    massSolar: 16.5,
    radiusSolar: 764,
    temperatureKelvin: 3600,
    spectralClass: 'M1-2 Ia-ab',
    ageGyr: 0.01,
    description: 'A semiregular pulsating red supergiant star expected to explode as a Type II supernova within the next 100,000 years.',
    scientificNotes: 'The Great Dimming of late 2019 to early 2020 was verified by SPHERE/VLT and Hubble observations to be caused by a massive surface mass ejection and subsequent dust condensation.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'ESO Very Large Telescope / SPHERE', dataset: 'Betelgeuse Surface Imaging', sourceType: 'Observatory' },
      { name: 'Montargès et al. (2021) Nature 594: A dusty veil shading Betelgeuse during its Great Dimming', sourceType: 'Peer-Reviewed Paper' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?auto=format&fit=crop&w=1200&q=80',
    color: '#EF4444',
    featured: true,
  },
  {
    id: 'proxima-centauri',
    name: 'Proxima Centauri',
    catalogDesignation: 'Alpha Centauri C / V645 Cen',
    alternativeNames: ['GL 551', 'HIP 70890'],
    type: 'Star',
    subType: 'Red Dwarf Flare Star (M5.5Ve)',
    constellation: 'Centaurus',
    coordinates: {
      ra: 217.4289,
      dec: -62.6795,
      raHMS: '14h 29m 42.9s',
      decDMS: '-62° 40\' 46"',
      frame: 'ICRS',
      distanceLy: 4.2465,
      distanceParsec: 1.302,
      galacticL: 313.9351,
      galacticB: -1.9169,
    },
    apparentMagnitude: 11.13,
    absoluteMagnitude: 15.6,
    distanceLy: 4.2465,
    massSolar: 0.1221,
    radiusSolar: 0.1542,
    temperatureKelvin: 3042,
    spectralClass: 'M5.5Ve',
    ageGyr: 4.85,
    discoveryYear: 1915,
    discoverer: 'Robert Innes',
    description: 'The closest known star to the Sun, hosting at least two confirmed exoplanets: Proxima b and Proxima d.',
    scientificNotes: 'Gravitationally bound to the Alpha Centauri AB binary system with an orbital period of ~550,000 years.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'ESA Gaia Data Release 3 (2022)', dataset: 'Gaia DR3 5853498713190525696', sourceType: 'Catalog' },
      { name: 'Anglada-Escudé et al. (2016) Nature: A terrestrial planet candidate in a temperate orbit around Proxima Centauri', sourceType: 'Peer-Reviewed Paper' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80',
    color: '#F87171',
    featured: false,
  },
  {
    id: 'm1-crab-nebula',
    name: 'Crab Nebula',
    catalogDesignation: 'Messier 1 / NGC 1952',
    alternativeNames: ['M1', 'Taurus A', 'SN 1054 Remnant'],
    type: 'Supernova Remnant',
    subType: 'Pulsar Wind Nebula',
    constellation: 'Taurus',
    coordinates: {
      ra: 83.6331,
      dec: 22.0145,
      raHMS: '05h 34m 31.9s',
      decDMS: '+22° 00\' 52"',
      frame: 'ICRS',
      distanceLy: 6500,
      distanceParsec: 2000,
      galacticL: 184.5575,
      galacticB: -5.7843,
    },
    apparentMagnitude: 8.4,
    distanceLy: 6500,
    massSolar: 4.6,
    radiusKm: 3.1e13,
    discoveryYear: 1731,
    discoverer: 'John Bevis (and recorded by Chinese astronomers in 1054 AD)',
    description: 'Supernova remnant from the historical SN 1054 explosion, powered by a rapidly rotating neutron star (Crab Pulsar, 30 revs/sec).',
    scientificNotes: 'Continuous synchrotron emission generated by relativistic electrons spiraling in the intense magnetic field of the pulsar.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'NASA Chandra X-ray Observatory & Hubble Space Telescope', sourceType: 'Observatory' },
      { name: 'Green, D.A. (2002) Historical Supernovae', sourceType: 'Peer-Reviewed Paper' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80',
    color: '#06B6D4',
    featured: true,
  },
  {
    id: 'm104-sombrero',
    name: 'Sombrero Galaxy',
    catalogDesignation: 'Messier 104 / NGC 4594',
    alternativeNames: ['M104'],
    type: 'Galaxy',
    subType: 'Unbarred Spiral Galaxy (SA(s)a)',
    constellation: 'Virgo',
    coordinates: {
      ra: 189.9976,
      dec: -11.6231,
      raHMS: '12h 39m 59.4s',
      decDMS: '-11° 37\' 23"',
      frame: 'ICRS',
      distanceLy: 29350000,
      distanceParsec: 9000000,
      galacticL: 298.4385,
      galacticB: 51.1576,
    },
    apparentMagnitude: 8.98,
    distanceLy: 29350000,
    massSolar: 8e11,
    description: 'A magnificent edge-on galaxy featuring a brilliant white bulbous core encircled by thick dark dust lanes.',
    scientificNotes: 'Hosts a central supermassive black hole of approximately 1 billion solar masses, one of the most massive in the nearby universe.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Hubble Heritage Project / NASA', sourceType: 'Observatory' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?auto=format&fit=crop&w=1200&q=80',
    color: '#FBBF24',
    featured: false,
  },
  {
    id: 'trappist-1',
    name: 'TRAPPIST-1',
    catalogDesignation: '2MASS J23062928-0502285',
    alternativeNames: ['K2-112'],
    type: 'Star',
    subType: 'Ultra-Cool Red Dwarf (M8V)',
    constellation: 'Aquarius',
    coordinates: {
      ra: 346.622,
      dec: -5.0414,
      raHMS: '23h 06m 29.3s',
      decDMS: '-05° 02\' 29"',
      frame: 'ICRS',
      distanceLy: 40.66,
      distanceParsec: 12.47,
      galacticL: 68.6186,
      galacticB: -57.7773,
    },
    apparentMagnitude: 18.8,
    distanceLy: 40.66,
    massSolar: 0.0898,
    radiusSolar: 0.1192,
    temperatureKelvin: 2566,
    spectralClass: 'M8V',
    ageGyr: 7.6,
    discoveryYear: 1999,
    description: 'An ultra-cool red dwarf star hosting a resonant chain of seven Earth-sized terrestrial planets, three of which orbit within the habitable zone.',
    scientificNotes: 'Planetary masses constrained with high precision through Transit Timing Variations (TTV) analysis.',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Gillon et al. (2017) Nature 542: Seven temperate terrestrial planets around the nearby ultracool dwarf star TRAPPIST-1', sourceType: 'Peer-Reviewed Paper' },
      { name: 'JWST Transiting Exoplanet Community ERS Team', sourceType: 'Observatory' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1447433589675-4aaa569f3e05?auto=format&fit=crop&w=1200&q=80',
    color: '#C084FC',
    featured: true,
  },
];

export const SOLAR_SYSTEM_BODIES: SolarSystemBody[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'Sun',
    orderFromSun: 0,
    color: '#FBBF24',
    textureColor: '#F59E0B',
    radiusKm: 695700,
    massKg: '1.989e+30',
    massEarthRelative: 333000,
    radiusEarthRelative: 109.2,
    semiMajorAxisAU: 0,
    eccentricity: 0,
    inclinationDeg: 0,
    orbitalPeriodDays: 0,
    orbitalVelocityKmS: 0,
    rotationPeriodHours: 609.12,
    axialTiltDeg: 7.25,
    surfaceTempKelvinMean: 5778,
    surfaceTempKelvinMin: 4100, // Sunspot
    surfaceTempKelvinMax: 15700000, // Core
    atmosphericComposition: ['Hydrogen: 73.46%', 'Helium: 24.85%', 'Oxygen: 0.77%', 'Carbon: 0.29%', 'Iron: 0.16%'],
    surfaceGravityMs2: 274.0,
    knownMoonsCount: 0,
    description: 'The G-type main-sequence star at the center of our Solar System, comprising 99.86% of the system\'s total mass.',
    notableFeatures: ['Thermonuclear p-p chain core fusion', 'Solar magnetic 11-year sunspot cycle', 'Coronal mass ejections and solar wind'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Solar Dynamics Observatory (SDO)', sourceType: 'Observatory' }],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Planet',
    orderFromSun: 1,
    color: '#9CA3AF',
    textureColor: '#6B7280',
    radiusKm: 2439.7,
    massKg: '3.3011e+23',
    massEarthRelative: 0.0553,
    radiusEarthRelative: 0.3829,
    semiMajorAxisAU: 0.3871,
    eccentricity: 0.2056,
    inclinationDeg: 7.005,
    orbitalPeriodDays: 87.969,
    orbitalVelocityKmS: 47.36,
    rotationPeriodHours: 1407.6,
    axialTiltDeg: 0.034,
    surfaceTempKelvinMean: 440,
    surfaceTempKelvinMin: 100,
    surfaceTempKelvinMax: 700,
    atmosphericComposition: ['Oxygen (exosphere): 42%', 'Sodium: 29%', 'Hydrogen: 22%', 'Helium: 6%'],
    surfaceGravityMs2: 3.7,
    knownMoonsCount: 0,
    description: 'The smallest and innermost planet, locked in a 3:2 spin-orbit resonance with extreme day-night temperature swings.',
    notableFeatures: ['Relativistic perihelion precession of 43 arcsec/century', 'Massive metallic iron core (85% of planet radius)', 'Caloris Basin impact structure'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA MESSENGER Mission Data Archive', sourceType: 'Space Mission' }],
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Planet',
    orderFromSun: 2,
    color: '#F59E0B',
    textureColor: '#D97706',
    radiusKm: 6051.8,
    massKg: '4.8675e+24',
    massEarthRelative: 0.815,
    radiusEarthRelative: 0.9499,
    semiMajorAxisAU: 0.7233,
    eccentricity: 0.0067,
    inclinationDeg: 3.394,
    orbitalPeriodDays: 224.701,
    orbitalVelocityKmS: 35.02,
    rotationPeriodHours: -5832.5, // Retrograde
    axialTiltDeg: 177.36,
    surfaceTempKelvinMean: 737,
    surfaceTempKelvinMin: 730,
    surfaceTempKelvinMax: 750,
    atmosphericComposition: ['Carbon Dioxide: 96.5%', 'Nitrogen: 3.5%', 'Sulfur Dioxide: 150 ppm'],
    surfaceGravityMs2: 8.87,
    knownMoonsCount: 0,
    description: 'Earth\'s "twin" in size and mass, enveloped in a dense runaway greenhouse atmosphere with 92 bars of surface pressure.',
    notableFeatures: ['Runaway carbon dioxide greenhouse effect', 'Retrograde slow rotation (day is longer than year)', 'Sulfuric acid cloud decks'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'ESA Venus Express & NASA Magellan Radar Mapping', sourceType: 'Space Mission' }],
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Planet',
    orderFromSun: 3,
    color: '#3B82F6',
    textureColor: '#2563EB',
    radiusKm: 6371.0,
    massKg: '5.9724e+24',
    massEarthRelative: 1.0,
    radiusEarthRelative: 1.0,
    semiMajorAxisAU: 1.0000,
    eccentricity: 0.0167,
    inclinationDeg: 0.000,
    orbitalPeriodDays: 365.256,
    orbitalVelocityKmS: 29.78,
    rotationPeriodHours: 23.934,
    axialTiltDeg: 23.44,
    surfaceTempKelvinMean: 288,
    surfaceTempKelvinMin: 184,
    surfaceTempKelvinMax: 330,
    atmosphericComposition: ['Nitrogen: 78.08%', 'Oxygen: 20.95%', 'Argon: 0.93%', 'Carbon Dioxide: 0.04%'],
    surfaceGravityMs2: 9.807,
    knownMoonsCount: 1,
    description: 'The third planet from the Sun and the only astronomical object known to harbor life and stable liquid water oceans.',
    notableFeatures: ['Active plate tectonics and geodynamo magnetic field', 'Hydrological water cycle with oceans covering 71% of surface', 'Dense nitrogen-oxygen biosphere'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Earth Observatory & USGS Planetary Cartography', sourceType: 'Observatory' }],
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Planet',
    orderFromSun: 4,
    color: '#EF4444',
    textureColor: '#DC2626',
    radiusKm: 3389.5,
    massKg: '6.4171e+23',
    massEarthRelative: 0.107,
    radiusEarthRelative: 0.532,
    semiMajorAxisAU: 1.5237,
    eccentricity: 0.0934,
    inclinationDeg: 1.850,
    orbitalPeriodDays: 686.98,
    orbitalVelocityKmS: 24.07,
    rotationPeriodHours: 24.623,
    axialTiltDeg: 25.19,
    surfaceTempKelvinMean: 210,
    surfaceTempKelvinMin: 130,
    surfaceTempKelvinMax: 308,
    atmosphericComposition: ['Carbon Dioxide: 95.32%', 'Nitrogen: 2.6%', 'Argon: 1.9%', 'Oxygen: 0.13%'],
    surfaceGravityMs2: 3.72,
    knownMoonsCount: 2,
    description: 'The Red Planet, featuring iron oxide-rich regolith, immense ancient shield volcanoes, and evidence of past liquid water flows.',
    notableFeatures: ['Olympus Mons (tallest planetary volcano at 21.9 km)', 'Valles Marineris (4,000 km long canyon network)', 'Seasonal carbon dioxide and water ice polar caps'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Perseverance / Curiosity / MRO Mars Global Data', sourceType: 'Space Mission' }],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Planet',
    orderFromSun: 5,
    color: '#D97706',
    textureColor: '#B45309',
    radiusKm: 69911,
    massKg: '1.8982e+27',
    massEarthRelative: 317.8,
    radiusEarthRelative: 10.97,
    semiMajorAxisAU: 5.2044,
    eccentricity: 0.0489,
    inclinationDeg: 1.303,
    orbitalPeriodDays: 4332.59,
    orbitalVelocityKmS: 13.07,
    rotationPeriodHours: 9.925,
    axialTiltDeg: 3.13,
    surfaceTempKelvinMean: 165, // 1 bar level
    atmosphericComposition: ['Hydrogen: 89.8%', 'Helium: 10.2%', 'Methane: 0.3%', 'Ammonia: 0.026%'],
    surfaceGravityMs2: 24.79,
    knownMoonsCount: 95,
    description: 'The Solar System\'s largest planet, a gas giant with more mass than all other planets combined and a colossal magnetosphere.',
    notableFeatures: ['Great Red Spot anticyclonic storm (observed for >350 years)', 'Metallic hydrogen mantle generating immense magnetic dipole', 'Four massive Galilean moons: Io, Europa, Ganymede, Callisto'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Juno Spacecraft & Galileo Orbiter', sourceType: 'Space Mission' }],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Planet',
    orderFromSun: 6,
    color: '#FCD34D',
    textureColor: '#FBBF24',
    radiusKm: 58232,
    massKg: '5.6834e+26',
    massEarthRelative: 95.16,
    radiusEarthRelative: 9.14,
    semiMajorAxisAU: 9.5826,
    eccentricity: 0.0565,
    inclinationDeg: 2.485,
    orbitalPeriodDays: 10759.22,
    orbitalVelocityKmS: 9.68,
    rotationPeriodHours: 10.656,
    axialTiltDeg: 26.73,
    surfaceTempKelvinMean: 134,
    atmosphericComposition: ['Hydrogen: 96.3%', 'Helium: 3.25%', 'Methane: 0.45%'],
    surfaceGravityMs2: 10.44,
    knownMoonsCount: 146,
    description: 'Renowned for its expansive and intricate planetary ring system composed predominantly of water ice and silicate dust.',
    notableFeatures: ['Majestic ring system spanning 282,000 km with only ~10 meters thickness', 'Hexagonal jet stream storm pattern at North Pole', 'Titan (dense nitrogen atmosphere) & Enceladus (cryovolcanic ocean)'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA/ESA Cassini-Huygens Mission Data', sourceType: 'Space Mission' }],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Planet',
    orderFromSun: 7,
    color: '#67E8F9',
    textureColor: '#22D3EE',
    radiusKm: 25362,
    massKg: '8.6810e+25',
    massEarthRelative: 14.54,
    radiusEarthRelative: 3.98,
    semiMajorAxisAU: 19.2184,
    eccentricity: 0.0463,
    inclinationDeg: 0.773,
    orbitalPeriodDays: 30685.4,
    orbitalVelocityKmS: 6.80,
    rotationPeriodHours: -17.24, // Retrograde
    axialTiltDeg: 97.77,
    surfaceTempKelvinMean: 76,
    surfaceTempKelvinMin: 49,
    atmosphericComposition: ['Hydrogen: 82.5%', 'Helium: 15.2%', 'Methane: 2.3%'],
    surfaceGravityMs2: 8.69,
    knownMoonsCount: 28,
    description: 'An ice giant with a dramatic 98° axial tilt, rolling on its side along its 84-year orbit around the Sun.',
    notableFeatures: ['Extreme 97.8° axial tilt creating 42-year long seasonal daylight and darkness', 'Coldest planetary atmosphere in the Solar System (down to 49 K)', 'Complex tilted off-center magnetic field'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Voyager 2 Flyby & Keck AO Observations', sourceType: 'Space Mission' }],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Planet',
    orderFromSun: 8,
    color: '#3B82F6',
    textureColor: '#1D4ED8',
    radiusKm: 24622,
    massKg: '1.0241e+26',
    massEarthRelative: 17.15,
    radiusEarthRelative: 3.86,
    semiMajorAxisAU: 30.0700,
    eccentricity: 0.0095,
    inclinationDeg: 1.769,
    orbitalPeriodDays: 60189.0,
    orbitalVelocityKmS: 5.43,
    rotationPeriodHours: 16.11,
    axialTiltDeg: 28.32,
    surfaceTempKelvinMean: 72,
    atmosphericComposition: ['Hydrogen: 80.0%', 'Helium: 19.0%', 'Methane: 1.5%'],
    surfaceGravityMs2: 11.15,
    knownMoonsCount: 16,
    description: 'The outermost major planet, an intense azure ice giant with supersonic winds exceeding 2,100 km/h.',
    notableFeatures: ['Fastest recorded planetary wind speeds in the solar system (>2,100 km/h)', 'Internal heat source radiating 2.61× the energy received from the Sun', 'Large retrograde captured Kuiper Belt moon Triton with nitrogen geysers'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA Voyager 2 Flyby & JWST NIRCam Imaging (2022)', sourceType: 'Space Mission' }],
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'Dwarf Planet',
    orderFromSun: 9,
    color: '#D1D5DB',
    textureColor: '#9CA3AF',
    radiusKm: 1188.3,
    massKg: '1.303e+22',
    massEarthRelative: 0.0022,
    radiusEarthRelative: 0.186,
    semiMajorAxisAU: 39.482,
    eccentricity: 0.2488,
    inclinationDeg: 17.16,
    orbitalPeriodDays: 90560.0,
    orbitalVelocityKmS: 4.74,
    rotationPeriodHours: -153.29,
    axialTiltDeg: 122.53,
    surfaceTempKelvinMean: 44,
    atmosphericComposition: ['Nitrogen: 99%', 'Methane: 0.5%', 'Carbon Monoxide: 0.05%'],
    surfaceGravityMs2: 0.62,
    knownMoonsCount: 5,
    description: 'The premier Kuiper Belt dwarf planet, featuring nitrogen ice glaciers, water-ice mountains, and a binary system with Charon.',
    notableFeatures: ['Sputnik Planitia: convective nitrogen-ice glacier basin', 'Tidally locked binary barycenter outside Pluto\'s surface with Charon', 'Chaotic orbital resonance 3:2 with Neptune'],
    evidenceStatus: 'OBSERVED',
    sources: [{ name: 'NASA New Horizons Mission Encounter (2015)', sourceType: 'Space Mission' }],
  },
];

export const EXOPLANET_CATALOG: ExoplanetData[] = [
  {
    id: 'trappist-1e',
    name: 'TRAPPIST-1 e',
    hostStar: 'TRAPPIST-1',
    hostStarSpectralType: 'M8V',
    distanceLy: 40.66,
    orbitalPeriodDays: 6.0996,
    semiMajorAxisAU: 0.0293,
    eccentricity: 0.0051,
    radiusEarth: 0.920,
    massEarth: 0.692,
    discoveryMethod: 'Transit',
    discoveryYear: 2017,
    equilibriumTempKelvin: 251, // -22°C, close to Earth's 255K equilibrium
    insolationFluxEarthRelative: 0.662,
    isPotentiallyHabitableCandidate: true,
    habitabilityNotes: 'Temperate rocky terrestrial planet receiving 66% of Earth insolation. High Earth Similarity Index (ESI 0.85). Prime candidate for atmospheric characterization by JWST.',
    surfaceGravityEarthRelative: 0.82,
    densityGcm3: 5.65,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'NASA Exoplanet Archive', dataset: 'Planetary Systems Composite Parameters', sourceType: 'Catalog', url: 'https://exoplanetarchive.ipac.caltech.edu' },
      { name: 'Grimm et al. (2018) Astronomy & Astrophysics: The nature of the TRAPPIST-1 exoplanets', sourceType: 'Peer-Reviewed Paper' },
    ],
    atmosphereNotes: 'Atmospheric transmission spectroscopy ongoing with JWST NIRSpec/MIRI.',
  },
  {
    id: 'kepler-452b',
    name: 'Kepler-452 b',
    hostStar: 'Kepler-452',
    hostStarSpectralType: 'G2V',
    distanceLy: 1402,
    orbitalPeriodDays: 384.84,
    semiMajorAxisAU: 1.046,
    eccentricity: 0.035,
    radiusEarth: 1.63,
    massEarth: 3.29,
    discoveryMethod: 'Transit',
    discoveryYear: 2015,
    equilibriumTempKelvin: 265,
    insolationFluxEarthRelative: 1.10,
    isPotentiallyHabitableCandidate: true,
    habitabilityNotes: 'Super-Earth candidate orbiting a Sun-like G2V star with a 385-day orbital period within the conservative habitable zone.',
    surfaceGravityEarthRelative: 1.24,
    densityGcm3: 4.19,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Jenkins et al. (2015) The Astronomical Journal: Discovery and Validation of Kepler-452b', sourceType: 'Peer-Reviewed Paper' },
      { name: 'NASA Exoplanet Archive', sourceType: 'Catalog' },
    ],
  },
  {
    id: 'proxima-centauri-b',
    name: 'Proxima Centauri b',
    hostStar: 'Proxima Centauri',
    hostStarSpectralType: 'M5.5Ve',
    distanceLy: 4.2465,
    orbitalPeriodDays: 11.186,
    semiMajorAxisAU: 0.0485,
    eccentricity: 0.109,
    radiusEarth: 1.07,
    massEarth: 1.173,
    discoveryMethod: 'Radial Velocity',
    discoveryYear: 2016,
    equilibriumTempKelvin: 234,
    insolationFluxEarthRelative: 0.65,
    isPotentiallyHabitableCandidate: true,
    habitabilityNotes: 'The closest known exoplanet candidate to Earth. Resides in the star\'s liquid-water habitable zone, though host star flares present potential atmospheric stripping risks.',
    surfaceGravityEarthRelative: 1.02,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'ESO HARPS & ESPRESSO Spectrograph Data', sourceType: 'Observatory' },
      { name: 'Suárez Mascareño et al. (2020) Revisiting Proxima with ESPRESSO', sourceType: 'Peer-Reviewed Paper' },
    ],
  },
  {
    id: 'toi-700-d',
    name: 'TOI-700 d',
    hostStar: 'TOI-700',
    hostStarSpectralType: 'M2V',
    distanceLy: 101.4,
    orbitalPeriodDays: 37.426,
    semiMajorAxisAU: 0.163,
    eccentricity: 0.032,
    radiusEarth: 1.144,
    massEarth: 1.72,
    discoveryMethod: 'Transit',
    discoveryYear: 2020,
    equilibriumTempKelvin: 269,
    insolationFluxEarthRelative: 0.86,
    isPotentiallyHabitableCandidate: true,
    habitabilityNotes: 'Earth-sized planet orbiting in the habitable zone of an inactive quiet M dwarf with low flare activity.',
    surfaceGravityEarthRelative: 1.31,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'NASA Transiting Exoplanet Survey Satellite (TESS)', dataset: 'Sector 11-13 Light Curves', sourceType: 'Space Mission' },
      { name: 'Gilbert et al. (2020) The First Habitable-zone Earth-sized Planet from TESS', sourceType: 'Peer-Reviewed Paper' },
    ],
  },
  {
    id: 'k2-18-b',
    name: 'K2-18 b',
    hostStar: 'K2-18',
    hostStarSpectralType: 'M2.5V',
    distanceLy: 124.0,
    orbitalPeriodDays: 32.9448,
    semiMajorAxisAU: 0.1429,
    eccentricity: 0.09,
    radiusEarth: 2.61,
    massEarth: 8.63,
    discoveryMethod: 'Transit',
    discoveryYear: 2015,
    equilibriumTempKelvin: 279,
    insolationFluxEarthRelative: 1.22,
    isPotentiallyHabitableCandidate: false,
    habitabilityNotes: 'Sub-Neptune / Hycean candidate with confirmed carbon-bearing molecules (CH4, CO2) detected in its atmosphere by JWST NIRISS/NIRSpec.',
    surfaceGravityEarthRelative: 1.27,
    densityGcm3: 2.67,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Madhusudhan et al. (2023) Carbon-bearing Molecules in a Possible Hycean Atmosphere on K2-18 b with JWST', sourceType: 'Peer-Reviewed Paper' },
      { name: 'NASA Exoplanet Archive', sourceType: 'Catalog' },
    ],
    atmosphereNotes: 'Detected CH4 and CO2 with tentative hints of dimethyl sulfide (DMS).',
  },
  {
    id: '51-pegasi-b',
    name: '51 Pegasi b (Dimidium)',
    hostStar: '51 Pegasi (Helvetios)',
    hostStarSpectralType: 'G5V',
    distanceLy: 50.45,
    orbitalPeriodDays: 4.230785,
    semiMajorAxisAU: 0.0527,
    eccentricity: 0.013,
    radiusJupiter: 1.27,
    radiusEarth: 14.2,
    massJupiter: 0.472,
    massEarth: 150.0,
    discoveryMethod: 'Radial Velocity',
    discoveryYear: 1995,
    equilibriumTempKelvin: 1265,
    isPotentiallyHabitableCandidate: false,
    habitabilityNotes: 'Archetypal "Hot Jupiter", historical first exoplanet discovered orbiting a main-sequence solar-type star (Nobel Prize in Physics 2019).',
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Mayor, Michel & Queloz, Didier (1995) Nature 378: A Jupiter-mass companion to a solar-type star', sourceType: 'Peer-Reviewed Paper' },
      { name: 'Observatoire de Haute-Provence (ELODIE)', sourceType: 'Observatory' },
    ],
  },
  {
    id: 'lhs-1140-b',
    name: 'LHS 1140 b',
    hostStar: 'LHS 1140',
    hostStarSpectralType: 'M4.5V',
    distanceLy: 48.8,
    orbitalPeriodDays: 24.737,
    semiMajorAxisAU: 0.0936,
    eccentricity: 0.043,
    radiusEarth: 1.73,
    massEarth: 5.60,
    discoveryMethod: 'Transit',
    discoveryYear: 2017,
    equilibriumTempKelvin: 226,
    insolationFluxEarthRelative: 0.43,
    isPotentiallyHabitableCandidate: true,
    habitabilityNotes: 'Prime rocky Super-Earth / Water World candidate orbiting in the habitable zone with high surface gravity (1.87 g) capable of retaining a thick volatile-rich atmosphere.',
    surfaceGravityEarthRelative: 1.87,
    densityGcm3: 5.9,
    evidenceStatus: 'OBSERVED',
    sources: [
      { name: 'Dittmann et al. (2017) Nature: A temperate rocky super-Earth transiting a nearby cool star', sourceType: 'Peer-Reviewed Paper' },
      { name: 'Cadieux et al. (2024) JWST transmission observations of LHS 1140 b', sourceType: 'Peer-Reviewed Paper' },
    ],
  },
];

export const APOD_ARCHIVE: APODRecord[] = [
  {
    date: '2026-09-07',
    title: 'JWST Deep Field: Cosmic Web and Gravitational Lenses in SMACS 0723',
    explanation: 'Thousands of galaxies—including the faintest objects ever observed in the infrared—have appeared in James Webb Space Telescope’s sharp view. This deep slice of the vast universe covers a patch of sky approximately the size of a grain of sand held at arm’s length by someone on the ground. The combined mass of this galaxy cluster acts as a gravitational lens, magnifying much more distant galaxies behind it.',
    url: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1600&q=85',
    hdurl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=2400&q=95',
    media_type: 'image',
    copyright: 'NASA, ESA, CSA, STScI, Webb ERO Team',
    evidenceStatus: 'OBSERVED',
  },
  {
    date: '2026-09-06',
    title: 'The Pillars of Creation in M16: Star Formation in Eagle Nebula',
    explanation: 'NASA’s James Webb Space Telescope captured a lush, highly detailed landscape—the iconic Pillars of Creation—where new stars are forming within dense clouds of interstellar gas and dust. The three-dimensional pillars look like majestic rock formations, but are far more permeable. These columns are made up of cool interstellar gas and dust that appear—at times—semi-transparent in near-infrared light.',
    url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=85',
    hdurl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=2400&q=95',
    media_type: 'image',
    copyright: 'NASA, ESA, CSA, STScI, J. DePasquale (STScI)',
    evidenceStatus: 'OBSERVED',
  },
  {
    date: '2026-09-05',
    title: 'Ring Nebula M57: The Glowing Death Shroud of a Sun-like Star',
    explanation: 'The Ring Nebula (M57), some 2,500 light-years away, is a planetary nebula created when a dying dying star ejected its outer layers of gas. Webb’s high-resolution images show not only the intricate details of the expanding shell, but also the inner region around the central white dwarf in unprecedented clarity.',
    url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1600&q=85',
    hdurl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=2400&q=95',
    media_type: 'image',
    copyright: 'ESA/Webb, NASA, CSA, M. Barlow, N. Cox, R. Wesson',
    evidenceStatus: 'OBSERVED',
  },
];

export const APOD_RECORDS = APOD_ARCHIVE;

export const CONSTELLATIONS_CATALOG = [
  { name: 'Ursa Major', latin: 'Ursa Major', abbr: 'UMa', centerRA: 160, centerDec: 55, stars: ['Dubhe', 'Merak', 'Phecda', 'Megrez', 'Alioth', 'Mizar', 'Alkaid'] },
  { name: 'Orion', latin: 'Orion', abbr: 'Ori', centerRA: 85, centerDec: 0, stars: ['Betelgeuse', 'Rigel', 'Bellatrix', 'Saiph', 'Alnitak', 'Alnilam', 'Mintaka'] },
  { name: 'Cassiopeia', latin: 'Cassiopeia', abbr: 'Cas', centerRA: 15, centerDec: 60, stars: ['Schedar', 'Caph', 'Gamma Cas', 'Ruchbah', 'Segin'] },
  { name: 'Cygnus', latin: 'Cygnus', abbr: 'Cyg', centerRA: 305, centerDec: 45, stars: ['Deneb', 'Albireo', 'Sadr', 'Gienah', 'Delta Cyg'] },
  { name: 'Scorpius', latin: 'Scorpius', abbr: 'Sco', centerRA: 250, centerDec: -30, stars: ['Antares', 'Shaula', 'Sargas', 'Dschubba', 'Graffias'] },
  { name: 'Taurus', latin: 'Taurus', abbr: 'Tau', centerRA: 65, centerDec: 15, stars: ['Aldebaran', 'Elnath', 'Alcyone (Pleiades)', 'Tianguan'] },
  { name: 'Pegasus', latin: 'Pegasus', abbr: 'Peg', centerRA: 340, centerDec: 20, stars: ['Markab', 'Scheat', 'Algenib', 'Enif'] },
];

export const BRIGHT_STARS_CATALOG = [
  { name: 'Sirius', designation: 'Alpha Canis Majoris', ra: 101.287, dec: -16.716, mag: -1.46, spectral: 'A1V', distLy: 8.6, constellation: 'Canis Major' },
  { name: 'Canopus', designation: 'Alpha Carinae', ra: 95.987, dec: -52.695, mag: -0.74, spectral: 'F0II', distLy: 310, constellation: 'Carina' },
  { name: 'Rigil Kentaurus', designation: 'Alpha Centauri A', ra: 219.902, dec: -60.833, mag: -0.01, spectral: 'G2V', distLy: 4.37, constellation: 'Centaurus' },
  { name: 'Arcturus', designation: 'Alpha Boötis', ra: 213.915, dec: 19.182, mag: -0.05, spectral: 'K1.5III', distLy: 36.7, constellation: 'Boötes' },
  { name: 'Vega', designation: 'Alpha Lyrae', ra: 279.234, dec: 38.783, mag: 0.03, spectral: 'A0Va', distLy: 25.0, constellation: 'Lyra' },
  { name: 'Capella', designation: 'Alpha Aurigae', ra: 79.172, dec: 45.998, mag: 0.08, spectral: 'G3III', distLy: 42.9, constellation: 'Auriga' },
  { name: 'Rigel', designation: 'Beta Orionis', ra: 78.634, dec: -8.201, mag: 0.13, spectral: 'B8Ia', distLy: 860, constellation: 'Orion' },
  { name: 'Procyon', designation: 'Alpha Canis Minoris', ra: 114.825, dec: 5.224, mag: 0.34, spectral: 'F5IV-V', distLy: 11.5, constellation: 'Canis Minor' },
  { name: 'Betelgeuse', designation: 'Alpha Orionis', ra: 88.793, dec: 7.407, mag: 0.50, spectral: 'M1-2Ia-ab', distLy: 548, constellation: 'Orion' },
  { name: 'Achernar', designation: 'Alpha Eridani', ra: 24.428, dec: -57.236, mag: 0.46, spectral: 'B6Vep', distLy: 139, constellation: 'Eridanus' },
  { name: 'Hadar', designation: 'Beta Centauri', ra: 210.956, dec: -60.373, mag: 0.61, spectral: 'B1III', distLy: 390, constellation: 'Centaurus' },
  { name: 'Altair', designation: 'Alpha Aquilae', ra: 297.695, dec: 8.868, mag: 0.77, spectral: 'A7V', distLy: 16.7, constellation: 'Aquila' },
  { name: 'Aldebaran', designation: 'Alpha Tauri', ra: 68.980, dec: 16.509, mag: 0.85, spectral: 'K5III', distLy: 65.3, constellation: 'Taurus' },
  { name: 'Antares', designation: 'Alpha Scorpii', ra: 247.351, dec: -26.432, mag: 0.96, spectral: 'M1.5Iab', distLy: 550, constellation: 'Scorpius' },
  { name: 'Spica', designation: 'Alpha Virginis', ra: 201.298, dec: -11.161, mag: 0.97, spectral: 'B1III-IV', distLy: 250, constellation: 'Virgo' },
  { name: 'Pollux', designation: 'Beta Geminorum', ra: 116.328, dec: 28.026, mag: 1.14, spectral: 'K0III', distLy: 33.78, constellation: 'Gemini' },
  { name: 'Fomalhaut', designation: 'Alpha Piscis Austrini', ra: 344.412, dec: -29.622, mag: 1.16, spectral: 'A3V', distLy: 25.13, constellation: 'Piscis Austrinus' },
  { name: 'Deneb', designation: 'Alpha Cygni', ra: 310.357, dec: 45.280, mag: 1.25, spectral: 'A2Ia', distLy: 2615, constellation: 'Cygnus' },
  { name: 'Regulus', designation: 'Alpha Leonis', ra: 152.092, dec: 11.967, mag: 1.35, spectral: 'B8IVn', distLy: 79.3, constellation: 'Leo' },
  { name: 'Polaris', designation: 'Alpha Ursae Minoris', ra: 37.954, dec: 89.264, mag: 1.98, spectral: 'F7Ib', distLy: 433, constellation: 'Ursa Minor' },
];
